### ISSUE TITLE
I cannot define more than one L.Geoserver.wfs separate layer

### ISSUE THREAD

**Issue by nez** [iamtekson/leaflet-geoserver-request#11]
When I try to make two or more layers with L.Geoserver.wfs, my layers break (The first layers don't show in the map, and the last layer shows the first layer instead of the correct one.

I want to fix it, but I need assistance, I don't understand the source of the bug

To reproduce see this fork where I tried to define 2 layers wfs1 and wfs2 https://github.com/nez/leaflet-geoserver-request/blob/e1bd8687147950fbc514d9f07e2f27e985a2b6f8/examples/maps.html#L61-L89
(In this example I am trying to make two layers with the same dataset, the first is red, and the second is white with half transparency, so the color should look pale red but it shows white.

There is also the following error in the browser 
 parsererror Error: getJson was not called
 Uncaught ReferenceError: getJson is not defined
 
 
 Thanks for the great lib and for your assistance

**Comment by iamtekson** [comment]
I see, I am also not sure why you are getting this error. Can you try with the two different layers, something like below,

```js
  var wfs1 = L.Geoserver.wfs("https://localhost:8080/geoserver/wfs", {
    layers: `demo:layer1`
  });

var wfs2 = L.Geoserver.wfs("https://localhost:8080/geoserver/wfs", {
    layers: `demo:layer2`
  });

  wfs1.addTo(map);
  wfs2.addTo(map);
```

**Comment by dameattrio** [comment]
I see this is a couple years old, but I'm facing the same problem. Was there ever any resolution? I'm hosting postGIS, GeoServer and Leaflet via nginx all on docker. I've got multiple layers in Geoserver and whenever I do a L.Geoserver.wfs() request more than twice, I get the same error in console. I'm attempting to call several different layers, no two layers are the same. I'll have two working and introduce a third, and the second one stops working, etc. 

`wfs-related snippet, can provide more

    var countyBoundary = L.Geoserver.wfs('https://example.com/geoserver/ows?service=WFS&', {
  		layers: "ccps:countyBoundary",
  		style: {
    		color: "black",
    		fillOpacity: 0,
    		opacity: 0.75,
			dashArray: (10, 10),
  		},
	}).addTo(map);

	var magisterialDistricts = L.Geoserver.wfs('https://example.com/geoserver/ows?service=WFS&', {
  		layers: "ccps:magisterialDistrict",
		style: {
			color: "green",
			opacity: 0.75,
			dashArray: (10, 10),
		},
		onEachFeature: function (feature, layer) {
    		layer.bindPopup(feature.properties.magdistnam);
  		},
	}).addTo(map);

	var elementaryBoundary = L.Geoserver.wfs('https://example.com/geoserver/ows?service=WFS&', {
  		layers: "ccps:elementaryBoundary",
		style: {
			color: "blue",
			opacity: 0.75,
			dashArray: (10, 10),
		},
		onEachFeature: function (feature, layer) {
    		layer.bindPopup(feature.properties.schoolname);
  		},
	}).addTo(map);`



console error:
parsererror Error: getJson was not called
Uncaught ReferenceError: getJson is not defined

What other info would be helpful?
