### ISSUE TITLE
Benefits of  leaflet-geoserver-request over L.tileLayer.wms

### ISSUE THREAD

**Issue by mylesmc123** [iamtekson/leaflet-geoserver-request#12]
I am wondering if there are particular use cases for Using leaflet-geoserver-request over leaflet.tileLayer.wms or if both exist just due to development history and features coming available at different times.

**Comment by iamtekson** [comment]
WMS request is the same as the leaflet.tileLayer.wms. But in this plugin, some of the default parameters from the leaflet are changed.
